// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class DemoContext : DbContext
{
    public DemoContext(DbContextOptions<DemoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Course { get; set; }

    public virtual DbSet<Person> Person { get; set; }

    public virtual DbSet<Student> Student { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.Property(e => e.Fee).HasMaxLength(50);
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.PhoneNumber).HasMaxLength(12);
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.Property(e => e.ClassName).HasMaxLength(50);

            entity.HasOne(d => d.Course).WithMany(p => p.Student)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK_Course_Student");

            entity.HasOne(d => d.Person).WithMany(p => p.Student)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_Person_Student");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}